kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-world-manifest-workspace
  namespace: hello-world-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-csi
  volumeMode: Filesystem
