---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type:
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: quay.io/rseip/hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: hello-world
  labels:
    app: hello-world
spec:
  selector:
      app: hello-world
  ports:
    - name: web
      port: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world-route
  namespace: hello-world
spec:
  to:
    kind: Service
    name: hello-world-svc
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: hello-world
  endpoints:
    - port: web
      path: /actuator/prometheus
