apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hello-world
  namespace: argocd
  istio-injection: enabled
spec:
  destination:
    namespace: hello-world
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/prod
    repoURL: 'https://github.com/rseip-rh/hello-world-deploy.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
