apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-tekton
spec:
  destination:
    namespace: hello-world-pipeline
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: tekton
    repoURL: 'https://gitlab.demo.rseip.dev/redhat/hello-world.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
